### ISSUE TITLE
Full example miss the SQS service integration example

### ISSUE THREAD

**Issue by rgarrigue** [terraform-aws-modules/terraform-aws-step-functions#64]
## Is your request related to a problem? Please describe.

The full example create a SQS queue in the extra resources part, which is unused. And there's no SQS in the service_integrations. 

## Describe the solution you'd like.

Add a SQS something to the service_integrations of the full example

**Comment by antonbabenko** [comment]
There is service integration for SQS - https://github.com/terraform-aws-modules/terraform-aws-step-functions/blob/master/locals.tf#L32C3-L39

I agree that we can remove SQS queue resource from the example since working with it is no different than working with other resources described in service_integrations - https://github.com/terraform-aws-modules/terraform-aws-step-functions/blob/master/examples/complete/main.tf#L47

PR is welcome.
